name: tinytex_windows
'on':
  push:
    branches:
    - master
    - main
    - RELEASE_**
  pull_request:
    branches:
    - master
    - main
    - RELEASE_**
jobs:
  tinytex_windows:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})
    container: ${{ matrix.config.cont }}
    strategy:
      fail-fast: ${{ false }}
      matrix:
        config:
        - os: windows-latest
          r: latest
          bioc: release
    steps:
    - uses: actions/checkout@v3
    - name: Install latex
      uses: r-lib/actions/setup-tinytex@v2 
      env:
        # install full prebuilt version
        TINYTEX_INSTALLER: TinyTeX
          
    - name: Install additional LaTeX packages
      run: |
        tlmgr install bera
        tlmgr list --only-installed
      shell: pwsh
